version: '3.9'
services:

  app:
    build: .
    environment:
      - ENVIRONMENT=prod
    env_file: .env
    container_name: tg-bot-voice-to-text
    image: 1kovalevskiy/tg-bot-voice-to-text:latest
    command: ["/app", "--config-path=/config.yml"]
    volumes:
      - ./config.yml:/config.yml
